littlefs-project/littlefs

.travis.yml, lfs.c, lfs.h
Here's a proposal for versioning littlefs.
In this patch, littlefs provides two version numbers at compile time, with major and minor parts, in the form of 6 macros.
``` c
LFS_VERSION        // Library version, uint32_t encoded
LFS_VERSION_MAJOR  // Major - Backwards incompatible changes
LFS_VERSION_MINOR  // Minor - Feature additions
LFS_DISK_VERSION        // On-disk version, uint32_t encoded
LFS_DISK_VERSION_MAJOR  // Major - Backwards incompatible changes
LFS_DISK_VERSION_MINOR  // Minor - Feature additions
```
Note that littlefs will error if it finds a major version number that is different, or a minor version number that has regressed.
related https://github.com/geky/littlefs/issues/10
=> Add version info for software library and on-disk structures

.travis.yml, Makefile, lfs.c, lfs.h, lfs_util.h, tests/test.py
This PR has several minor changes to littlefs that would improve support for porting to new platforms. A lot of these has been requested in issues or have been notable sources of problems (cough intrinsics cough).
This will also be the first minor version bump of littlefs. So we'll see how that goes. Feel free to leave feedback here.
What's new:
- Big-endian support (untested at the moment, will test before merge)
- Better default bitwise intrinsics (lfs_ctz/lfs_popc) with pure C fallbacks
- Better distinction between macros that require no side-effects
- System includes are only brought in when needed
- Malloc/free wrappers
- LFS_NO_* checks for quickly disabling things at the command line
Related issues:
- https://github.com/geky/littlefs/issues/6 (malloc/free/assert wrappers requested) …
=> Add better general support in lfs_utils.h

LICENSE.md, emubd/lfs_emubd.c, emubd/lfs_emubd.h, lfs.c, lfs.h, lfs_util.c, lfs_util.h
We're changing the license from Apache-2.0 to [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) for better compatibility with GPL v2. More info here: https://github.com/ARMmbed/littlefs/issues/59
This change comes with a minor version bump to v1.4 for visibility.
Any PRs made before v1.4 will need to be rebased to include the updated license. Thanks for the support everyone.
should resolve https://github.com/ARMmbed/littlefs/issues/59
cc @sg-, @jlovejoy, @Sim4n6, @aldot, @jrast
=> v1.4 - Change license to BSD-3-Clause

Makefile, lfs.c, lfs_util.h, tests/test_files.sh, tests/test_seek.sh
First off, thanks for this project!  It's nice and clean and integrates well into other embedded systems.
In this PR I've fixed a few compiler warnings, when `-Wshadow` and `-Wunused-parameter` are enabled.  Fixing these help to integrate littlefs in bigger projects that have these warnings enabled, without applying additional workarounds.
I also added a commit to enable these warnings in the Makefile here, so the problems don't crop up again.
Any feedback is most welcome.
=> Fix some compiler warnings: shadowed variable and unused parameters

Makefile
1. Added check for main.c and test.c to decide compilation target
2. Added step to remove test.c after successful test completion
The test.c file, which contains the expanded test main, is useful when debugging why tests are failing. However, keeping the test.c file around causes problems when a later attempt is made to compile a larger project containing the littlefs directory.
Under (hopefully) normal operation, tests always pass. So it should be ok to remove the test.c file after a successful test run. Hopefully this behaviour doesn't cause too much confusion for contributors using the
tests.
On the other side of things, compiling the library with no main ends (successfully) with the "main not found" error message. By defaulting to lfs.a if neither test.c/main.c is avoid this in the …
=> Add quality of life improvements for main.c/test.c issues 

.travis.yml
This was causing code sizes to be reported with several of the logging functions still built in. A useful number, but not the minimum achievable code size.
=> Fix script issue with bash expansion inside makefile parameter

emubd/lfs_emubd.c, lfs.c
When using `"%d"` or `"%x"` with `uint32_t` types, arm-none-eabi-gcc reports
warnings like below:
```
In file included from lfs.c:8:
lfs_util.h:45:12: warning: format '%d' expects argument of type 'int', but argument 4 has type 'lfs_block_t' {aka 'long unsigned int'} [-Wformat=]
printf("lfs debug:%d: " fmt "\n", __LINE__, __VA_ARGS__)
^~~~~~~~~~~~~~~~
lfs.c:2512:21: note: in expansion of macro 'LFS_DEBUG'
LFS_DEBUG("Found partial move %d %d",
^~~~~~~~~
lfs.c:2512:55: note: format string is defined here
LFS_DEBUG("Found partial move %d %d",
~^
%ld
```
Fix this by replacing `"%d"` and `"%x"` with `"%" PRIu32` and `"%" PRIx32`.
=> Use PRIu32 and PRIx32 format specifiers to fix warnings

emubd/lfs_emubd.h, lfs.h, lfs_util.h
Even though it is perfectly possible to surround `#include "lfs.h"` with `extern "C" { ... }` directly in the C++ files, the common practice is to have such C++ guards directly in headers, even if this is a C library. The maintenance cost is basically zero (just remember to add includes "outside" the guards and code "inside"), while the gains are important (at least in my opinion):
1. Generally all C libraries do that, so it is a common practice, expected by people developing in C++. This is also true for C system headers like `stddef.h` (see `_BEGIN_STD_C` and `_END_STD_C` macros from newlib as an example) and so on.
2. If the header does not follow this common practice and application does not surround the `#include` with `extern "C" { ... }`, the project compiles perfectly fine, with …
=> Add C++ guards to public headers

lfs.c, lfs.h
The `LFS_NO_MALLOC` option is very useful, because some systems have very particular memory allocation needs.  But enabled this option doesn't allow to have multiple files open at the same time.  This PR adds a quick fix for this by allowing to pass in the `file_buffer` directly to `lfs_file_open()`, so the latter doesn't need to call `lfs_malloc()`.
I don't expect this to be merged as-is because it breaks the existing API.  But a feature along these lines would be very useful because it gives full functionality of littlefs without the need for any `malloc()` or `free()` functions.
Alternatives to this PR would be:
- a new function, eg `lfs_file_open_using()` which accepts the 5th parameter added here
- allow to set the global `lfs->cfg->file_buffer` pointer before each call to …
=> Added possibility to open multiple files with LFS_NO_MALLOC enabled

.travis.yml
Previously, littlefs had mutable versions. That is, anytime a new commit landed on master, the bot would update the most recent version to contain the patch. The idea was that this would make sure users always had the most recent bug fixes. Immutable snapshots could be accessed through the git hashes.
However, at this point multiple developers have pointed out that this is confusing, with mutable versions being non-standard and surprising.
This new release process adopts SemVer in its entirety, with incrementing patch numbers and immutable versions.
When a new commit lands on master:
1. The major/minor version is taken from lfs.h
2. The most recent patch version is looked up on GitHub and incremented
3. A changelog is built out of the commits to the previous version
4. A new release and …
=> Simplified release process based on feedback

LICENSE.md, README.md
This makes is a bit easier to find the description about the SPDX tags, and fixes the issue where GitHub doesn't detect the license text.
cc @jlovejoy
=> Moved SPDX and license info into README

lfs.c
The lfs_cache_zero function that was recently added assumed a single cache size, which is incorrect. This would cause a buffer overflow if read_size != prog_size.
Since lfs_cache_zero is only used for scrubbing prog caches, the fix here is to use lfs_cache_drop instead on read caches. Info in read caches should never make its way to disk.
Should resolve https://github.com/ARMmbed/littlefs/issues/89
=> Fix issue with corruption due to different cache sizes

emubd/lfs_emubd.c
This will create default stats file if it doesn't exist.
=> If stats file doesn't exist lfs_emubd_create will fail.

lfs.c, lfs.h, tests/test_dirs.sh
The issue happens when a rename causes a split in the destination pair. If the destination pair is the same as the source pair, this triggers the logic to keep both pairs in sync. Unfortunately, this logic didn't work, because the source entry still resides in the old source pair, unlike the destination pair, which is now in the new pair created by the split.
The best fix for now is to refetch the source pair after the changes to the destination pair. This isn't the most efficient solution, but fortunately this bug has already been fixed in the revamped move logic in littlefs v2 (currently in progress).
Found by @ohoc
Should resolve https://github.com/ARMmbed/littlefs/issues/110
=> Fix issue where a rename causes a split and pushes dir out of sync

lfs.c, lfs.h
On disk, littlefs uses 32-bit integers to track file size. This sets a theoretical limit of 4GiB for files.
However, the API passes file sizes around as signed numbers, with negative values representing error codes. This means that not all of the APIs will work with file sizes > 2GiB.
Because of related complications over in FUSE land, I've added the LFS_FILE_MAX constant and proper error reporting if file writes/seeks exceed the 2GiB limit. In v2 this will join the other constants that get stored in the superblock to help portability. Since littlefs is targeting microcontrollers, it's likely this will be a sufficient solution.
Note that it's still possible to enable partial-support for 4GiB files by defining LFS_FILE_MAX during compilation. This will work for most of the APIs, except …
=> Add 2GiB file size limit and EFBIG reporting

lfs.c
To make lfs_file_truncate inline with ftruncate function, when -ve
or size more than maximum file size is passed to function it should
return invalid parameter error. In LFS case LFS_ERR_INVAL.
Signed-off-by: Ajay Bhargav <contact@rickeyworld.info>
=> Fix: length more than LFS_FILE_MAX should return error

lfs.h
lfs_dir_read breaks the convention of returning non-zero on success,
this feature should be at least documented.
This already caused some confusion in issue https://github.com/ARMmbed/littlefs/issues/114 . The documentation was not clear about return values. This PR clarifies the return values, including those that are not covered by standard error codes.
=> Fixed documentation for return lfs_dir_read return value.

lfs.c
In some cases specific alignment of buffer passed to underlying device
is required. For example SDMMC in STM32F7 (when used with DMA) requires
the buffers to be aligned to 16 bytes. If you enable data cache in
STM32F7, the alignment of buffer passed to any driver which uses DMA
should generally be at least 32 bytes.
While it is possible to provide sufficiently aligned "read", "prog" and
per-file caches to littlefs, the cases where caches are bypassed are
hard to control when littlefs is hidden under some additional layers.
For example if you couple littlefs with stdio and use it via `FILE*`,
then littlefs functions will operate on internal `FIlE*` buffer, usually
allocated dynamically, so in these specific cases - with insufficient
alignment (8 bytes on ARM Cortex-M).
The easy path was …
=> Don't bypass cache in `lfs_cache_prog()` and `lfs_cache_read()`

lfs.c
When LFS1 code is present and LFS_MIGRATE is enabled
=> Make lfs1_crc static so it doesn't conflict with prefixed LFS1 code

scripts/prefix.py, tests/corrupt.py, tests/stats.py, tests/test.py
On some systems, `python` links to `python3`, so the tests fail to run.
Would there be interest in converting all these to Python 3? Since Python 2 is due for deprecation this year... I could send a PR for this. If so, is Python >=3.6 acceptable? Asking because of f-strings.
=> Mark all Python 2 scripts as Python 2

lfs.c
The data written to the prog cache would make littlefs internally
consistent, but because this was never written to disk, the filesystem
would become unmountable.
Unfortunately, this wasn't found during testing because caches automatically
flush if data is written up to a program boundary (maybe this was a mistake?).
Also changed lfs_migrate and lfs_format to erase the backup superblock per suggestion from @rojer. This will help prevent accidentally picking up outdated filesystem versions that may have been corrupted (discussion in #182).
Should fix https://github.com/ARMmbed/littlefs/issues/182
=> Fix missing cache flush in lfs_migrate, force lfs_migrate to erase v1

lfs.c, tests/test_seek.sh
The cause was mistakenly setting file->ctz.size directly instead of
file->pos, which file->ctz.size gets overwritten with later in
lfs_file_flush.
Also added better seek test cases specifically for inline files. This
should also catch most of the inline corner cases related to
lfs_file_size/lfs_file_tell.
Should fix https://github.com/ARMmbed/littlefs/issues/172
=> Fix accidental truncate after seek on inline files

emubd/lfs_emubd.c
On some architectures `<dirent.h>` is not available (preventing the code from compiling); meanwhile, the code does not appear to use any of [the documented functionality of the same](https://pubs.opengroup.org/onlinepubs/7908799/xsh/dirent.h.html):
> ##### [ ]()DESCRIPTION
> 
> The internal format of directories is unspecified.
> 
> > The _&lt;dirent.h&gt;_ header defines the following data type through **typedef**:
> 
> DIR
> 
> A type representing a directory stream.
> 
> > It also defines the structure **dirent** which includes the following members:
> 
> ino_t  d_ino       file serial number
> char   d_name[]    name of entry
> 
> > The type **ino_t** is defined as described in _[&lt;sys/types.h&gt;](https://pubs.opengroup.org/onlinepubs/7908799/xsh/systypes.h.html)_.
> 
> > The …
=> removed <dirent.h> preventing compile on some archs

lfs.h
The size of the lookahead buffer is required to be a multiple of 8 bytes
in anticipation of a future improvement.  The buffer itself need only be
aligned to support access through a uint32_t pointer.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
=> lfs: correct documentation on lookahead-related values

lfs.h
Found by @joel-felcana in https://github.com/ARMmbed/littlefs/issues/212
- lfs_file_rewind == lfs_file_seek(lfs, file, 0, LFS_SEEK_SET)
- lfs_file_seek returns the _new_ position of the file
=> Fixed seek-related typos in lfs.h

lfs.c, lfs.h
Do not allow some file operations to (re)use lfs_file_t stucture when file is already opened (prohibit open) or not opened/closed (prohibit all operations but open).
It is achieved by adding new internal file flag. This flag is set in lfs_file_open and it is reset in lfs_file_close. It is also tested in each (file related) API call as an ASSERTprecondition.
This is second attempt to add this functionality after discussion in pull request [#213](https://github.com/ARMmbed/littlefs/pull/213).
=> Protect (LFS_ASSERT) file operations against using not opened or closed files.

emubd/lfs_emubd.c
More info here https://github.com/ARMmbed/littlefs/issues/229
Found by @DanielLyubin
Should fix https://github.com/ARMmbed/littlefs/issues/229
=> Fix overlapping memcpy in emubd

lfs.c
Previously these returned LFS_ERR_BADF. But attempting to modify a file
opened read-only, or reading a write-only flie, is a user error and
should not occur in normal use.
Changing this to an assert allows the logic to be omitted if the user
disables asserts to reduce the code footprint (not suggested unless the
user really really knows what they're doing).
I'm making this change because I can't think of any use cases where an error code would be helpful. But let me know if I'm missing a use case.
=> Change rdonly/wronly mistakes to assert

lfs.c
Due to the logging nature of metadata pairs, switching from inline files
(type3 = 0x201) to CTZ skip-lists (type3 = 0x202) does not explicitly
erase inline files, but instead leaves them up to compaction to omit.
To save code size, this is handled by the same logic that deduplicates
tags.
Unfortunately, this wasn't working. Due to a relatively late change in v2
the struct's type field was changed to no longer be a part of determining a
tag's "uniqueness". A part of this should have been the modification of
directory traversal filtering to respect type-dependent uniqueness, but
I missed this.
The fix is to add in correct type-dependent filtering. Also there was
some clean up necessary around removing delete tags during compaction
and outlining files.
Note that while this appears to …
=> Fix issue where inline files were not cleaned up

.travis.yml, Makefile, emubd/lfs_emubd.c, emubd/lfs_emubd.h, lfs.c, tests/template.fmt, tests/test_files.sh
A current limitation of the lfs tag is the 10-bit (1024) length field.
This field is used to indicate padding for commits and effectively
limits the size of commits to 1KiB. Because commits must be prog size
aligned, this is a problem on devices with prog size > 1024.
```
[----                   6KiB erase block                   ----]
[-- 2KiB prog size --|-- 2KiB prog size --|-- 2KiB prog size --]
[ 1KiB commit |  ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ]
```
This can be increased to 12-bit (4096), but for NAND devices this is
still to small to completely solve the issue.
The previous workaround was to just create unaligned commits. This can
occur naturally if littlefs is used on portable media as the prog size
does not have to be consistent on different drivers. If littlefs sees …
=> Fix issues with large prog sizes (prog_size > 1KiB)

.travis.yml, lfs.c, lfs.h
As it is now, block_cycles = 0 disables wear leveling. This was a mistake. 0 is the "default" value for several other config options and makes it easy to accidentally disable wear-leveling. It's even worse when migrating from v1 as it's easy to miss the addition of block_cycles and end up with a filesystem that is not actually wear-leveling.
Clearly, block_cycles = 0 should do anything but disable wear-leveling.
Here, I've changed block_cycles = 0 to assert. Forcing users to set a value for block_cycles (500 is suggested). block_cycles can be set to -1 to explicitly disable wear leveling if desired.
Related: https://github.com/ARMmbed/littlefs/issues/189
=> Change block_cycles disable from 0 to -1

.travis.yml
This is a result of feedback that the current release notes made it too difficult to see what changes happened on patch releases. From my experience as well it became difficult to chase down which release a commit landed on.
The risk is that this creates additional noise, both for the release page and for user notifications. I am open to feedback if this causes a problem.
Other tweaks on the CI side, these came from iteration with the same scheme for coru and equeue:
- Changed version branch updates to be atomic (vN and vN-prefix). This makes it a bit easier to fix if one of the pushes fails due to a rogue branch with the same name.
- Added GEKY_BOT_DRAFT as a CI macro that can optionally switch between only creating drafts or immediately posting a release. The default is what I will be …
=> Changed CI to create release note for patches

lfs.c
The buffer need only be 32-bit aligned.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
=> lfs: correct alignment restriction on lookahead buffer

lfs.c, tests/test_truncate.sh
[ftruncate](https://pubs.opengroup.org/onlinepubs/009695399/functions/ftruncate.html) is not supposed to move the seek pointer, but when making a file smaller the littlefs code did this.
The third patch in this set closes #252.
The first two are cleanup patches that (IMO) make it easier for people to understand the code and work with the code: one changing magic numbers to meaningful symbols, and one ensuring the file `off` field is not left uninitialized during open.  I can remove either or both of those if they're not wanted.
=> fix seek position corruption in truncate function

Makefile, lfs.c
Part of https://github.com/mongoose-os-libs/vfs-fs-lfs/issues/2
=> Fix build with -Wundef

emubd/lfs_emubd.c
Certain functions within lfs_emubd.c were susceptible to file resource leaks due to certain code paths not issuing an fclose() before returning.
=> Fix for issue #260

lfs.c
Since `lfs_init` validates lfs config attributes, it should also check that the attributes are initiated properly, in order to not crash, for example, if `read_size` or `prog_size` or `cache_size` are not set (floating point excpetion).
Also, those attributes are really critical for lfs, and if the user didn't set those values, he must be aware of that (assertion error is pretty indicative, unlike a weird floating point exception..).
=> lfs: Validate lfs-cfg sizes before performing any arithmetic logics with them

README.md
An addition to 38a2a8d. When executing the given example in README, you immediately get an assertion error because block_cycles is initiated to 0.
=> Update readme example code in accordance to the block_cycles change

Makefile, lfs.c, tests/test_relocations.sh
This is caused by dir->head not being updated when dir->m.pair may be. This causes the two to fall out of sync and later dir rewinds to fail.
~**Note:** Needs tests, there may be other issues related to out-of-sync directory heads and seek/rewinds.~
EDIT: Has tests, but now it needs those tests to _work_
=> Fixed issue with directories falling out of date after block relocation

lfs.c
- Bad size used for writing out softtail tag
- Use of sizeof address instead of intended target
=> Fixed some issues in lfs_migrate

lfs.c
On my platform, `PRId32` resolves to `ld`.
With a return type of int, this is incorrect. Likewise, `%d` is incorrect for an `int32_t`. This commit fixes the various `LFS_TRACE` lines to fix compilation - my LFS_TRACE impl becomes a printf checked by gcc.
=> Fix some LFS_TRACE format specifiers

lfs.c
This is a fork of https://github.com/ARMmbed/littlefs/pull/185:
> -> call lfs_dir_fetchmatch with ftag=-1 in order to set the invalid bit and never let the function match a dir
Related to https://github.com/ARMmbed/littlefs/issues/184
=> fix nullptr access in lfs_dir_fetchmatch (#185)

README.md
PR created for https://github.com/ARMmbed/littlefs/issues/331:
> README: fix incorrect description
>
> In my point of view, file updates will commit to filesystem only when
sync or close. There is a extra word 'no' here.
> 
> Fixes: bdff4bc59eb6 ("Updated DESIGN.md to reflect v2 changes")
> Signed-off-by: liaoweixiong <liaoweixiong@allwinnertech.com>
=> README: fix incorrect description

lfs.c, tests/test_seek.sh
See https://github.com/ARMmbed/littlefs/issues/328
The superblock entry takes up id 0 in the root directory (not all entries are files, though currently the superblock is the only exception). Normally, reading a directory correctly skips the superblock and only reports non-superblock files.
However, this doesn't work perfectly for lfs_dir_seek, which tries to be clever to not touch the disk.
Fortunately, we can fix this by adding an offset for the superblock. This will only work while the superblock is the only non-file entry, otherwise we would need to touch the disk to properly seek in a
directory (though we already touch the disk a bit to get dir-tails during seeks).
Found by @jhartika
Related https://github.com/ARMmbed/littlefs/issues/328
=> Fix lfs_dir_seek/lfs_dir_tell mismatch

.travis.yml, lfs.c, tests/test_alloc.sh, tests/test_relocations.sh
Sometimes small, single line code change hides behind it a complicated story. This is one of those times.
If you look at this diff, you may note that this is a case of lfs_dir_fetchmatch not correctly handling a tag that invalidates a callback used to search for some condition, in this case a search for a parent, which is invalidated by a later dir tag overwritting the previous dir pair.
But how can this happen? Dir-pair-tags are only overwritten during relocations (when a block goes bad or exceeds the block_cycles config option for dynamic wear-leveling). Other dir operations create new directory entries. And the only lfs_dir_fetchmatch condition that relies on overwrites (as opposed to proper deletes) is when we need to find a directory's parent, an operation that only occurs during a …
=> Fixed lfs_dir_fetchmatch not understanding overwritten tags

lfs.c, tests/test_alloc.toml
(bugfix) adding line function to clear out all the global 'free' info…rmation so that we can reset it after a failed traversal
=> Lookahead corruption fix given an IO Error during traversal

lfs.c
This reverts commit fdd239fe21a3721dc7fb55a9cf816544af7e9647.
Bypassing cache turned out to be a mistake which causes more problems
than it solves. Device driver should deal with alignment if this is
required - trying to do that in a file system is not a viable solution
anyway.
#160
=> Revert "Don't bypass cache in `lfs_cache_prog()` and `lfs_cache_read()`"

lfs_util.h
The terminating comma does not get removed in non-MSVC compilers.  Use ## to consume the comma in this case, allowing zero-arg prints
=> Allow debug prints without __VA_ARGS__ in non-MSVC

lfs_util.h
`lfs_npw2` returns a value v such that `2^v >= a` and `2^(v-1) < a`, but
the previous comment incorrectly describes it as "less than or equal to
a".
=> Fix incorrect comment on `lfs_npw2`

README.md
As introduced in #297, I created a python wrapper for littlefs. The wrapper supports two API's: A C-like API which is the same as in C and a more pythonic API which is easier to use if you are more the python guy. The wrapper is built with littlefs 2.2.1 at the moment.
=> Added littlefs-python to the related projects section

bd/lfs_testbd.c
New PR because the previous PR is now unrestorable (https://github.com/littlefs-project/littlefs/pull/459)
> Fix for a minor annoyance where the testbd device uses assert rather than LFS_ASSERT
=> Fix assert

lfs.c, scripts/readtree.py
- Fixed incorrect modulus in lfs_alloc_reset
Modulus of the offset by block_size was clearly a typo, and should be block_count. Interesting to note that later moduluses during alloc calculations prevents this from breaking anything, but as gtaska notes it could skew the wear-leveling distribution.
- Removed unnecessary randomization of offsets in lfs_alloc_reset
On first read, randomizing the allocators offset may seem appropriate for lfs_alloc_reset. However, it ends up using the filesystem-fed pseudorandom seed in situations it wasn't designed for.
As noted by gtaska, the combination of using xors for feeding the seed and multiple traverses of the same CRCs can cause the seed to flip to zeros with concerning frequency.
Removed the randomization from lfs_alloc_reset, leaving it in only …
=> Fix several wear-leveling issues found in lfs_alloc_reset

lfs.c
It's very slowly to compare one byte at one time. Here are the
performance I get from 128M spinand with NFTL by sequential writing.
| file size | buffer size  | write speed  |
| 10 MB     | 0   B        | 3206.01 KB/s |
| 10 MB     | 1   B        | 2434.04 KB/s |
| 10 MB     | 2   B        | 2685.78 KB/s |
| 10 MB     | 4   B        | 2857.94 KB/s |
| 10 MB     | 8   B        | 3060.68 KB/s |
| 10 MB     | 16  B        | 3155.30 KB/s |
| 10 MB     | 64  B        | 3193.68 KB/s |
| 10 MB     | 128 B        | 3230.62 KB/s |
| 10 MB     | 256 B        | 3153.03 KB/s |
| 70 MB     | 0   B        | 2258.87 KB/s |
| 70 MB     | 1   B        | 1827.83 KB/s |
| 70 MB     | 2   B        | 1962.29 KB/s |
| 70 MB     | 4   B        | 2074.01 KB/s |
| 70 MB     | 8   B        | 2147.03 KB/s |
| 70 MB …
=> lfs_bd_cmp() compares more bytes at one time

lfs.c
Closes #429
Also fixed a magic number in `opencfg`
=> Assert that the file isnt open in lfs_file_opencfg

.travis.yml, lfs.c, lfs.h
This PR tries to solve #162 , by providing an `LFS_READONLY` define.
LittleFS seems to be preferred over SPIFFS in many places and projects right now.
However, for my bootloader / firmware upgrade use-case, the code size matters a lot.
A bootloader could do with a read-only version of the file system, which should be a lot smaller in size.
With SPIFFS I am able to get a read-only version without caching compiled to around 3 KB (compiled for Cortex-M0),
while the read-write version with caching weighs in at around 13 KB, which is comparable to LittleFS.
By defining out a bunch of write-related functionality, I was able to reduce the read-only version of LittleFS to around 5 KB for that same Cortex-M0 target, which seems acceptable for bootloader use.
I have separately `#ifdef`'ed every …
=> Add LFS_READONLY define, to allow smaller builds providing read-only mode

lfs.c, lfs.h, lfs_util.h
I'm working on an optional thread safe wrapper for the top level LittleFS APIs. I'm currently trying to sort out a few outstanding issues but the general design is there. When LFS_THREAD_SAFE is enabled all lfs calls will be routed through the locking wrappers otherwise all that code will be compiled out and function as normal.
We are testing using AWS IoT qualification tests but have not added any tests to the test suite.
Please let me know your thoughts.
=> Add thread safe wrappers

lfs.c
See https://github.com/littlefs-project/littlefs/issues/489 for more information.
This rather interesting corner-case arises in lfs_dir_alloc anytime the uninitialized revision count happens to be a multiple of block_cycles+1.
For example, the source of the bug found by tim-nordell-nimbelink:
```
rev = 2742492087
block_cycles = 100
2742492087 % (100+1) = 0
```
The reason for this weird block_cycles+1 case is due to a fix for a previous bug in fe957de. To avoid aliasing, which would cause metadata pairs to wear unevenly, block_cycles incremented to the next odd number.
Normally, littlefs tweaks the revision count of blocks during lfs_dir_alloc in order to make sure evictions can't happen on the first compact. Otherwise, higher-level logic such as lfs_format would break.
However, this …
=> Fix allocation-eviction issue when erase state is multiple of block_cycles+1

.travis.yml, README.md, bd/lfs_testbd.c, lfs.c, lfs.h, scripts/readtree.py
You may or may not have noticed a slight change to this repo's branches. There is now a [devel](https://github.com/littlefs-project/littlefs/tree/devel) branch, which for the near future, will act as a staging area for release before they are merged to master.
Is this an indirect method of having master/release branches? Maybe! But I'm still learning and this should help how fast I can merge PRs without committing to releases at the same time.
Anyways!
This PR brings in:
- #395 lfs_bd_cmp() compares more bytes at one time
- #412 Added littlefs-python to the related projects section
- #443 Assert that the file isnt open in lfs_file_opencfg
- #470 Add thread safe wrappers
- #480 Add LFS_READONLY define, to allow smaller builds providing read-only mode
- #486 Fix assert
- #487 Fix several …
=> Minor release: v2.3

lfs.c
lfs_mdir_isopen goes unused if asserts are disabled, and this caused an "unused function" warning on Clang (curiously not on GCC since the function was static inline, commonly used for header-only functions).
Also removed "inline" from the lfs_mdir_* functions as these involve linked-list operations and really shouldn't be inlined. And since they are static, inlining should occur automatically if there is a benefit.
Found by @dpgeorge
Should fix https://github.com/littlefs-project/littlefs/issues/498
=> Moved lfs_mdir_isopen behind LFS_NO_ASSERT

scripts/test.py
The argparse documented an outdated format, and was off by 1. Should fix https://github.com/littlefs-project/littlefs/issues/500.
Found by @sender6
=> Fixed incorrect documentation in test.py

lfs.c, lfs.h
Alright, hopefully I've done this correctly. Inspired by our conversation on #203.
Not sure of the best way to validate performance "properly", if there's a test bench already setup I should be using, but I am still seeing a 10x increase in directory traversal/file deletion and a 2x-4x speedup in file reads with this code and a `metadata_max` of 4096 and `inline_file_max` of -1.
Commit message:
We have seen poor read performance on NAND flashes with 128kB blocks.
The root cause is inline files having to traverse many sets of metadata
pairs inside the current block before being fully reconstructed. Simply
disabling inline files is not enough, as the metadata will still fill up
the block and eventually need to be compacted.
By allowing configuration of how much size metadata takes up, along …
=> Add metadata_max config to help performance on devices with large blocks

lfs.c
After a bit of tweaking in #193 to write out all superblocks during lfs_format, additional writes were added after the sanity checking normally done at the end.
This turned out to be a problem when porting littlefs, as it makes it easy for addressing issues to not get caught during lfs_format.
Helps https://github.com/littlefs-project/littlefs/issues/378
Found by @marekr, @tristanclare94, and @mjs513
=> Moved sanity check in lfs_format after compaction

lfs.c, tests/test_truncate.toml
This fixes #436.
@geky It appears that your concerns were valid, as one of the truncation test cases is now failing with this change:
```
====== results ======
tests/test_truncate.toml:96:failure: test_truncate#3#1 failed with -6
tests/test_truncate.toml:127:assert: assert failed with 48, expected eq 0
memcmp(rb, wb, trunc) => 0;
```
Do you have any ideas about how to go about resolving this?
=> Skip flushing file if lfs_file_rawseek() doesn't change position

.travis.yml, lfs.c, lfs.h
From the discussion in #503, I started to implement the split `LFS_ASSERT`/`LFS_ASSERT_RETURN` functionality, but realised that all but one assert already exists in a function returning `int` or `lfs_ssize_t`.
Thus, by changing this function to return `int`, I can continue to use my custom LFS_ASSERT impl:
`#define LFS_ASSERT(test) do {if(!(test)) {log_error("lfs ASSERT %s:%d ", __FILE__, __LINE__); return LFS_ERR_ASSERT;}} while(0)`
Though there aren't any checks in place to prevent newly written LFS_ASSERT-using functions from returning `void`, I added `LFS_ERR_ASSERT` to the `lfs_error` enum to hopefully encourage consistency. Happy to revert that part of the commit.
=> lfs_fs_preporphans: return int to alllow graceful LFS_ASSERT

README.md
The tests use `lfs_testbd.h`, not `lfs_emubd.h`, and the directory name is `bd`, not `emubd`.
=> Fix link to test block device

lfs.c
Without this patch, when defining `LFS_READONLY`:
```
littlefs/lfs.c:14:20: warning: unused function 'lfs_cache_drop' [-Wunused-function]
static inline void lfs_cache_drop(lfs_t *lfs, lfs_cache_t *rcache) {
^
littlefs/lfs.c:271:20: warning: unused function 'lfs_pair_sync' [-Wunused-function]
static inline bool lfs_pair_sync(
^
littlefs/lfs.c:283:20: warning: unused function 'lfs_pair_tole32' [-Wunused-function]
static inline void lfs_pair_tole32(lfs_block_t pair[2]) {
^
littlefs/lfs.c:368:20: warning: unused function 'lfs_gstate_hasorphans' [-Wunused-function]
static inline bool lfs_gstate_hasorphans(const lfs_gstate_t *a) {
^
littlefs/lfs.c:372:23: warning: unused function 'lfs_gstate_getorphans' [-Wunused-function]
static inline uint8_t lfs_gstate_getorphans(const lfs_gstate_t *a) {
^ …
```
=> Fix compiler warnings when LFS_READONLY defined

lfs.h
Fixes littlefs-project/littlefs#568
=> Specify unit of the size members of the lfs_config struct

bd/lfs_rambd.c
This fixes warnings produced by tools such as memcheck without requiring the user to set an erase value.
```
==3983== Use of uninitialised value of size 8
==3983==    at 0x114F2E: lfs_crc (lfs_util.c:25)
==3983==    by 0x10C3B4: lfs_dir_commitprog (lfs.c:1287)
==3983==    by 0x10D147: lfs_dir_compact (lfs.c:1695)
==3983==    by 0x10DE71: lfs_dir_commit (lfs.c:1959)
==3983==    by 0x1120C7: lfs_rawformat (lfs.c:3643)
==3983==    by 0x11383A: lfs_format (lfs.c:4938)
==3983==    by 0x1158EA: main (test.c:43)
...
==3983== Conditional jump or move depends on uninitialised value(s)
==3983==    at 0x10B1FE: lfs_dir_traverse (lfs.c:805)
==3983==    by 0x10B1A3: lfs_dir_traverse (lfs.c:786)
==3983==    by 0x10D1EC: lfs_dir_compact (lfs.c:1706)
==3983==    by 0x10DE71: lfs_dir_commit (lfs.c:1959) …
```
=> Always zero rambd buffer before first use

lfs.c
BUG CASE:Assume there are 6 blocks in littlefs, block 0,1,2,3 already allocated. 0 has a tail pair of {2, 3}. Now we try to write more into 0.
When writing to block 0, we will split(FIRST SPLIT), thus allocate block 4 and 5. Up to now , everything is as expected.
Then we will try to commit in block 4, during which split(SECOND SPLIT) is triggered again(In our case, some files are large, some are small, one split may not be enough).  Still as expected now.
BUG happens when we try to alloc a new block pair for the second split:
As lookahead buffer reaches the end , a new lookahead buffer will be generated from flash content, and block 4, 5 are unused blocks in the new lookahead buffer because they are not programed yet. HOWEVER, block 4,5 should be occupied in the first split!!!!!  The …
=> fix bug:lfs_alloc will alloc one block repeatedly in multiple split

lfs.c
When the on-disk block size doesn't match the config block size, it is
possible to get file corruption. For instance, if the num blocks was
0x200 and we re-mount with 0x100 files could be corrupt.
If we re-mount with a larger number of blocks things should be safer,
but could be handled with a resize option or perhaps a mount flag to
ignore this parameter.
=> Fail mount when the block size changes

lfs.c, lfs.h
fixing my previous fix
just prevent the use of lfs_file_open() when LFS_NO_MALLOC is set.
because it fails with the return code LFS_ERR_NOMEM due to lfs_malloc() returning NULL in lfs_file_rawopencfg (lfs.c:2578).
=> don't use lfs_file_open() when LFS_NO_MALLOC is set

lfs.c
This should fix the performance issue if a new seek position belongs to currently cached data.
This avoids unnecessary rereads of file data.
See [issue #631](https://github.com/littlefs-project/littlefs/issues/631)
=> Fix lfs_file_rawseek performance issue

lfs.c
While working on a `littlefs` integration I've received the return value `LFS_ERR_NAMETOOLONG` for several error scenarios where it doesn't apply. I think the affected line may have been copied by mistake.
E.g., I've received this return value for an invalid block device driver where I've messed up the offsets within the memory and also with bugs in an optimized CRC32 calculation.
=> Removed invalid overwrite for return value.

bd/lfs_filebd.c
There are two issues, when using the file-based block device emulation
on Windows Platforms:
1. There is no fsync implementation available. This needs to be mapped
to a Windows-specific FlushFileBuffers system call.
2. The block device file needs to be opened as binary file (O_BINARY)
The corresponding flag is not required for Linux.
=> Fixes to use lfs_filebd on windows platforms

LICENSE.md, bd/lfs_filebd.c, bd/lfs_filebd.h, bd/lfs_rambd.c, bd/lfs_rambd.h, bd/lfs_testbd.c, bd/lfs_testbd.h, lfs.c, lfs.h, lfs_util.c, lfs_util.h
Update the copyright notice to note the owner as the littlefs project moving forward.
This should have no impact on the current license (littlefs is still available under BSD 3-Clause), but just documents an ownership change.
littlefs was at one point funded by Arm under [Mbed OS](https://github.com/ARMmbed/mbed-os), but it hasn't been this way for a while. With the permission from the head of OSO at Arm, this has been moved into the category of personal project, with myself taking ownership. This is a mutual change as it clarifies that the direction of littlefs has zero reflection on Arm.
For full transparency, I'm still employed at Arm, but my work has little to do with littlefs at the moment. Anything I write here is my own. Employment aside, I'm personally still very interested in …
=> Update copyright notice

lfs.c
Rename can be VERY time consuming. One of the reasons is the 4 recursion
level depth of lfs_dir_traverse() seen if a compaction happened during the
rename.
```
[1] lfs_dir_traverse(cb=lfs_dir_commit_size)
- do 'duplicates and tag update'
[2] lfs_dir_traverse(cb=lfs_dir_traverse_filter, data=tag[1])
- Reaching a LFS_FROM_MOVE tag
[3] lfs_dir_traverse(cb=lfs_dir_traverse_filter, data=tag[1]) <= on 'from' dir
- do 'duplicates and tag update'
[4] lfs_dir_traverse(cb=lfs_dir_traverse_filter, data=tag[3])
```
Yet, analyse shows that levels [3] and [4] don't perform anything
if the callback is lfs_dir_traverse_filter...
A practical example:
- format and mount a 4KB block FS
- create 100 files of 256 Bytes named "/dummy_%d"
- create a 1024 Byte file "/test"
- rename "/test" "/test_rename"
- …
=> Optimization of the rename case.

.github/workflows/post-release.yml, .github/workflows/release.yml, .github/workflows/status.yml, .github/workflows/test.yml, .gitignore, LICENSE.md, Makefile, bd/lfs_filebd.c, bd/lfs_filebd.h, bd/lfs_rambd.c, bd/lfs_rambd.h, bd/lfs_testbd.c, bd/lfs_testbd.h, lfs.c, lfs.h, lfs_util.c, lfs_util.h, scripts/coverage.py, scripts/data.py, scripts/stack.py, scripts/structs.py, scripts/summary.py, scripts/test.py
Thanks for everyone who contributed and provided feedback!
Bringing in: 
- #584
- #614
- #630
- #632
- #638
- #643
- #657
- #658
- #666
- Removed all recursion ([#658](https://github.com/littlefs-project/littlefs/pull/658))
On paper, littlefs promises O(1) RAM consumption, however in practice, this hasn't quite been true due to the use of recursion in several parts of the implementation. 2 instances of recursion were bounded at runtime, but 1 instance could be unbounded, though this would require many block relocations to all occur simultaneously.
These pieces have now been rewritten to strictly avoid recursion, at the cost of some code size (<=5.1%). This means littlefs now lives up to its promise of bounded RAM, and the total RAM usage can be easily …
=> Minor release: v2.5

lfs.c
If you compile lfs.c with LFS_NO_MALLOC defined you get an unused function warning for `lfs_file_rawopen`.
If you're compiling with `-Werror` that becomes an error:
```
third_party/littlefs/lfs.c:3001:12: error: 'lfs_file_rawopen' defined but not used [-Werror=unused-function]
3001 | static int lfs_file_rawopen(lfs_t *lfs, lfs_file_t *file,
|            ^~~~~~~~~~~~~~~~
```
This pull request fixes the warning.
=> Fix unused function warning with LFS_NO_MALLOC

.github/workflows/test.yml, Makefile, lfs.c
This was a false positive, but having clean warnings in clang would be good to have. See https://github.com/littlefs-project/littlefs/issues/684 for more info.
Also added clang compilation to CI.
---
Note that I've also removed some of the extra warning flags applied to littlefs up until this point. Some are not available in clang, and I've been meaning to remove these for a while as I've not found them more annoying than useful.
Found by @dpgeorge
=> Fix self-assign warnings discovered by clang, remove some warning flags

lfs.h
Improve the lfs_file_close usage description to make it clearer that the configuration structure must remain valid for its lifetime
In reference to #722
=> Improve lfs_file_close usage description

.github/workflows/test.yml, Makefile, SPEC.md, bd/lfs_emubd.c, lfs.c, lfs.h, scripts/changeprefix.py, scripts/readmdir.py, tests/test_compat.toml, tests/test_powerloss.toml
Original issue here: https://github.com/littlefs-project/littlefs/issues/245#issuecomment-606050523
This is a proposal to fix the out-of-order writes found by @pjsg's fuzzing work.
The problem is that it is possible for (non-NOR) block devices to write pages in any order, or to even write random data in the case of a power-loss. This breaks littlefs's use of the first bit in a page to indicate the erase-state.
@pjsg notes this behavior is documented in the W25Q here:
https://community.cypress.com/docs/DOC-10507
---
The basic idea here is to CRC the next page, and use this "erase-state CRC" to check if the next page is erased and ready to accept programs.
```
.------------------. \   commit
|     metadata     | |
|                  | +---.
|                  | |   |
|------------------| | …
```
=> Forward-looking erase-state CRCs

lfs.c
The previous cycle detection algorithm (a naive check against the largest possible tail list) is simple and gets the job done, but has the potential to take a very long time on disks with many blocks. [Brent's algorithm](https://en.wikipedia.org/wiki/Cycle_detection#Brent's_algorithm), on the other hand, takes at most 2x the number of blocks in the tail list.
The naive cycle detection algorithm was originally chosen as I was only aware of [Floyd's algorithm](https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_tortoise_and_hare) at the time (the classic tortoise+hare cycle detection). Floyd's algorithm is a poor fit for littlefs as it requires managing two desynced traversals of the tail list, which comes with quite a bit of complexity+code cost. But Brent's algorithm is very well suited …
=> Adopt Brent's algorithm for cycle detection

README.md
This is a tool that I've been working on. It should be capable of opening littlefs disk images up to a size of 4 GiB and allows browsing the folder structure, "downloading" files from the file system, etc.
The tool doesn't support all of the features of littlefs yet (e.g., viewing folder attributes), but it's [getting there](https://github.com/tniessen/littlefs-disk-img-viewer).
=> Add littlefs-disk-img-viewer to README

README.md
"chamelon" implements a subset of littlefs (no global move state or
singly-linked list threaded through the directory tree) for use in the
MirageOS library operating system project. It is written entirely in
OCaml and is interoperable (with the above caveats) with the reference
implementation via FUSE.
=> Add "chamelon" to the related projects section.

README.md
See #788, originally created by @elpiel 
> The latest crate release supports 2.1.4, however, it's still a good idea to add the crate to your list 😋 imo
=> Add littlefs2 crate to README

lfs.c
This has caught enough people that an explicit assert is warranted.
How littlefs, a c99 project, should be integrated with c89 projects is still an open question, but no one deserves to debug this sort of undetected casting issue.
Found by @johnernberg and @XinStellaris. This an alternative to https://github.com/littlefs-project/littlefs/pull/772 and https://github.com/littlefs-project/littlefs/pull/677.
=> Add an assert for truthy-preserving bool conversions

lfs.c
See https://github.com/littlefs-project/littlefs/issues/264 for more info.
There was already an assert for this, but because it included the underlying equation for the requirement it was too confusing for users that had no prior knowledge for why the assert could trigger.
The math works out such that 128 bytes is a reasonable minimum requirement, so I've added that number as an explicit assert. Hopefully this makes this sort of situation easier to debug.
Note that this requirement would need to be increased to 512 bytes if block addresses are ever increased to 64-bits. [DESIGN.md#ctz-skip-lists](https://github.com/littlefs-project/littlefs/blob/master/DESIGN.md#ctz-skip-lists) goes into more detail why this is.
=> Add explicit assert for minimum block size of 128 bytes

lfs.c, tests/test_orphans.toml
The underlying issue is that lfs_fs_deorphan did not updating gstate correctly. The way it determined if there are any orphans remaining in the filesystem was by subtracting the number of found orphans from an internal counter.
This internal counter is a leftover from a previous implementation that allowed leaving the lfs_fs_deorphan loop early if we know the number of expected orphans. This can happen during recursive mdir relocations, but with only a single bit in the gstate, can't happen during mount. If we detect orphans during mount, we set this internal counter to 1, assuming we will find at least one orphan.
But this presents a problem, what if we find _no_ orphans? If this happens we never decrement the internal counter of orphans, so we would never clear the bit in the gstate. …
=> Fix issue where lfs_fs_deorphan may run more than needed

lfs.c, lfs.h, tests/test_orphans.toml
`lfs_fs_mkconsistent` allows running the internal consistency operations (desuperblock/deorphan/demove) on demand and without any other filesystem changes.
This can be useful for front-loading and persisting consistency operations when you don't want to pay for this cost on the first write to the filesystem.
https://github.com/littlefs-project/littlefs/blob/259535ee73a792556bb16eebfbd076f467c5bdfa/lfs.h#L680-L688
This also offers a way to force the on-disk minor version to bump, if that is wanted behavior. An on-disk minor version bump is being added in https://github.com/littlefs-project/littlefs/pull/497, so this is convenient timing.
---
Not entirely sure about the name, open to suggestions though I think this is an improvement over `lfs_fs_forceconsistency` which was really meant to …
=> Add lfs_fs_mkconsistent

tests/test_truncate.toml
When truncation is done on a file to the block size, there seems to be an error where it points to an incorrect block. Perform a write / truncate / readback operation to verify this issue.
Signed-off-by: Colin Foster <colin.foster@in-advantage.com>
=> Add test scenario for truncating to a block size

tests/test_dirs.toml
The tests don't actually test every file.
The iteration skips the two `.` and `..` directories, which means that the last two files were not read. This PR fixes that. This seems to reach an edge case reported in #785.
As can be seen, the tests fail at a call to `lfs_dir_seek`, when they shouldn't.
=> Add missing iterations in tests

.gitattributes
This reclassifies .toml files in littlefs as .c files for the purpose of GitHub's search/language detection.
With the new test framework, GitHub really wants to mark littlefs as a python project:
Telling GitHub to reclassify our test .toml files as C code (which they are 95% of anyways) remedies this.
An alternative would be to add syntax=c vim modelines to the test/bench files, which would also render them with C syntax highlighting on GitHub. Unfortunately the interspersed toml metadata mucks this up, making the result not very useful.
GitHub's language detection/workarounds are document over here:
https://github.com/github-linguist/linguist
This is low-priority, so will wait to merge it until there is another reason for a patch release.
=> Convince GitHub littlefs is a C project

lfs.c
This fixes the overflowing left shift on 8 bit platforms.
littlefs2/lfs.c: In function ‘lfs_dir_commitcrc’:
littlefs2/lfs.c:1654:51: error: left shift count >= width of type [-Werror=shift-count-overflow]
commit->ptag = ntag ^ ((0x80 & ~eperturb) << 24);
=> Fix build for AVR

lfs_util.h
Likely included at some point for `ssize_t`, this is no longer needed and causes some problems for embedded compilers.
Currently littlefs doesn't even use `size_t`/`ssize_t` in its definition of `lfs_size_t`/`lfs_ssize_t`, so I don't think this will ever be required.
Found by @LDong-Arm, @vvn-git
=> Remove unnecessary sys/types.h include

.github/workflows/test.yml, lfs.c, lfs.h, tests/test_compat.toml, tests/test_superblocks.toml
This is more-or-less cherry-picked from https://github.com/littlefs-project/littlefs/pull/753, which is paused for now.
`lfs_fs_stat` introduces a way to access some of the littlefs-specific status/configuration that hasn't been available yet. The intention is to be analogous the POSIX [statvfs](https://linux.die.net/man/2/statvfs):
``` c
// Find on-disk info about the filesystem
//
// Fills out the fsinfo structure based on the filesystem found on-disk.
// Returns a negative error code on failure.
int lfs_fs_stat(lfs_t *lfs, struct lfs_fsinfo *fsinfo);
```
The immediate benefit of this function is a way to get the minor version on disk, which @TjoBitDk noted was oddly missing in the recent release. This should resolve https://github.com/littlefs-project/littlefs/issues/826.
Currently …
=> Add lfs_fs_stat for access to filesystem status/configuration

README.md
ChaN's FAT implementation definitely deserves a mention here, since it was one of the first open-source microcontroller-oriented filesystem implementations that I'm aware of, and has a lot of good ideas at the implementation level.
Honestly I didn't realize this wasn't already linked to from here. If you're using FAT on a microcontroller, it's most likely this library.
=> Add a link to ChaN's FatFS implementation

bd/lfs_emubd.c, bd/lfs_emubd.h, bd/lfs_filebd.c, bd/lfs_filebd.h, bd/lfs_rambd.c, bd/lfs_rambd.h, lfs.c, lfs.h, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, tests/test_alloc.toml, tests/test_badblocks.toml, tests/test_exhaustion.toml, tests/test_superblocks.toml
This pull request attempts to autodetect the `block_count` from the superblock if not provided in `lfs_config` (i.e. `cfg->block_count == 0`).
This PR slightly increases RAM usage by increasing the `lfs_t` struct by 4 bytes.
~I think this PR could also negatively impact mounting performance (I refactored it so that the superblock search and the gstate search are independent), but I think those are super fast anyways. A possible organization improvement would be to abstract the traversal to another function, but that might reduce readability. We can leave that for another PR.~
~@geky currently this is set as a draft as I want to write more unit tests, but need some advice on how to debug. Currently one of the test permutations hangs; I don't quite understand what the permutations are or …
=> Infer block_count from superblock if not provided in config.

bd/lfs_emubd.c, bd/lfs_emubd.h, bd/lfs_filebd.c, bd/lfs_filebd.h, bd/lfs_rambd.c, bd/lfs_rambd.h, lfs.c, lfs.h, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, tests/test_alloc.toml, tests/test_badblocks.toml, tests/test_exhaustion.toml, tests/test_superblocks.toml
Originally proposed by @kaetemi, this API allows you to change the size of the filesystem on disk to take advantage of additional space if it becomes available:
``` c
cfg.block_count = 1024;
int err = lfs_mount(lfs, cfg);
if (err) {
return err;
}
struct lfs_fsstat fsstat;
err = lfs_fs_stat(lfs, &fsstat);
if (err) {
return err;
}
printf("block_count: %d\n", fsstat.block_count); // prints 1024
err = lfs_fs_grow(lfs, 2048);
if (err) {
return err;
}
struct lfs_fsstat fsstat;
err = lfs_fs_stat(lfs, &fsstat);
if (err) {
return err;
}
printf("block_count: %d\n", fsstat.block_count); // prints 2048
```
If you want to automatically resize littlefs to the full disk size every mount, this can be done by using these two calls as your "mount" operation:
``` c
lfs_size_t required_block_count = …
```
=> Add lfs_fs_grow to enable limited resizing of the filesystem

lfs.c, lfs.h, tests/test_alloc.toml
See https://github.com/littlefs-project/littlefs/pull/610 for more info, original PR by @opilat.
This API allows users to run the internal block allocator directly, which may allow users to move the expensive block scan out of performance sensitive parts of their codebase.
It should be noted this API does not current persist the results of the block scan on disk, so calling lfs_fs_gc and then remounting does nothing. This may change in the future.
=> Add lfs_fs_gc to enable proactive finding of free blocks

bd/lfs_emubd.c, bd/lfs_emubd.h, bd/lfs_filebd.c, bd/lfs_filebd.h, bd/lfs_rambd.c, bd/lfs_rambd.h, lfs.c, lfs.h, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, tests/test_alloc.toml, tests/test_badblocks.toml, tests/test_exhaustion.toml, tests/test_superblocks.toml
This release brings in some useful community-driven features. Thanks everyone who has put up PRs!
Bringing in:
- https://github.com/littlefs-project/littlefs/pull/866
- https://github.com/littlefs-project/littlefs/pull/872
- https://github.com/littlefs-project/littlefs/pull/875
---
This release brings in some useful community-driven features.
- Thanks to @BrianPugh, littlefs no longer needs the `block_count` when mounting an existing filesystem ([#866](https://github.com/littlefs-project/littlefs/pull/866))
Simply set `block_count=0` in your configuration, and littlefs will automatically determine the `block_count` based on what's on disk. This allows you to mount a filesystem of unknown size.
- Added `lfs_fs_grow` which allows you to change the size of an …
=> Minor release: v2.8

Makefile, lfs.c
Two new functions introduced in 2.6.0 (`lfs_fs_mkconsistent`, 259535ee73a792556bb16eebfbd076f467c5bdfa) and 2.8.0 (`lfs_fs_grow`, 23505fa9fa4f2d863f046c0bfad8db2ca63cfb90) have internal "raw" functions which are missing the `static` keyword.
This was causing build failures in our builds in the MicroPython project when updating to the latest LittleFS, because we're building with `-Werror,-Wmissing-prototypes,-Wmissing-declarations`. See [here](https://github.com/micropython/micropython/actions/runs/6561913228/job/17822696395) and [here](https://github.com/micropython/micropython/actions/runs/6575701921/job/17863464790) for the build output.
This PR adds the `static` keyword to these functions to fix these, similar to how all other internal functions in LittleFS are defined.
=> lfs_fs_raw* functions should be static

lfs.c
Superblock expansion is an irreversible operation. In an effort to prevent superblock expansion from claiming valuable scratch space (important for small, <~8 block filesystems), littlefs prevents superblock expansion when the disk is "mostly full".
In true computer-scientist fashion, this "mostly full" threshold was set to ~50%.
As pointed out by @gbolgradov and @rojer, >~50% utilization is not uncommon, and it can lead to a situation where superblock expansion does not occur in a relatively healthy filesystem, causing focused wear at the root.
To remedy this, the threshold is now increased to ~88% (7/8) full.
This may change in the future and should probably be eventually user configurable.
See https://github.com/littlefs-project/littlefs/issues/901 for more info.
=> Increase threshold for superblock expansion from ~50% -> ~88% full

.github/workflows/release.yml
This script was missed during a struct -> structs naming change.
=> Fix struct sizes missing from generated release notes

lfs.c, lfs.h
Added some sanity check for the user-providable `#define` macro values.
This was brought up due to a bug introduced by yours truly 💅  https://github.com/jrast/littlefs-python/issues/61
=> Add value-range checks for user-definable macros at compile-time

lfs_util.c, lfs_util.h
With this you can override littlefs's malloc/crc implementations with some simple defines:
```
-DLFS_MALLOC=my_malloc
-DLFS_FREE=my_free
-DLFS_CRC=my_crc
```
I think these are the main "system-level" utils that users want to override, but am open to feedback.
---
Note on LFS_CRC:
Overriding LFS_CRC with something that's not CRC32 is discouraged. Your filesystem will no longer be compatible with other tools. This is only intended for providing hardware acceleration, etc.
---
These are probably what most users expected when wanting to override malloc/free/crc in littlefs, but they haven't been available, since instead littlefs provides a file-level override of builtin utils behind LFS_CONFIG.
The thinking was that there's just too many builtins that could be overriden, …
=> Add some easier util overrides: LFS_MALLOC/FREE/CRC

lfs.c, lfs.h, lfs_util.h, tests/test_orphans.toml
This drops the lookahead buffer from operating on 32-bit words to operating on 8-bit bytes, and removes any alignment requirement. This may have some minor performance impact, but it is unlikely to be significant when you consider IO overhead.
The original motivation for 32-bit alignment was an attempt at future-proofing in case we wanted some more complex on-disk data structure. This never happened, and even if it did, it could have been added via additional config options.
This has been a significant pain point for users, as providing word-aligned byte-sized buffers in C can be a bit annoying.
---
This also includes a number of internal block allocator improvements, mostly around naming things and making the logic hopefully easier to understand.
=> Relaxed lookahead alignment, other internal block alloc readability improvements

lfs.c, lfs.h, lfs_util.h, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, tests/test_alloc.toml, tests/test_orphans.toml
This extends `lfs_fs_gc` to now handle three things:
1. Calls mkconsistent if not already consistent
2. Compacts metadata > `compact_thresh`
3. Populates the block allocator
Which should be all of the janitorial work that can be done without additional on-disk data structures.
Normally, metadata compaction occurs when an mdir is full, and results in mdirs that are at most `block_size/2`.
Now, if you call lfs_fs_gc, littlefs will eagerly compact any mdirs that exceed the `compact_thresh` configuration option. Because the resulting mdirs are at most `block_size/2`, it only makes sense for `compact_thresh` to be >= `block_size/2` and <= `block_size`.
Additionally, there are some special values:
- `compact_thresh=0`  => defaults to ~88% `block_size`, may change in the future
- …
=> Extend lfs_fs_gc to compact metadata, compact_thresh 

.github/workflows/post-release.yml, .github/workflows/release.yml, .github/workflows/status.yml, .github/workflows/test.yml
I ran into this issue on a different repo, GitHub phases out Ubuntu runners after some time, which results in CI just "waiting for runners" indefinitely.
If we already have to bump this version as GitHub phases out older Ubuntu runners (which is reasonable), I don't really see the value of pinning a specific version. We might as well just respond to any broken dependencies caused by GitHub's implicit updates as they happen...
It's not like CI is truly continuous.
=> Change CI to just run on ubuntu-latest

lfs.c, tests/test_dirs.toml
When lfs_rename() is called trying to rename (move) a file to an existing directory, LFS_ERR_ISDIR is (correctly) returned. However, in the opposite case, if one tries to rename (move) a directory to a path currently occupied by a regular file, LFS_ERR_NOTDIR should be returned (since the error is that the destination is NOT a directory), but in reality, LFS_ERR_ISDIR is returned in this case as well.
This commit fixes the code so that in the latter case, LFS_ERR_NOTDIR is returned.
=> Fix return value of lfs_rename()

bd/lfs_emubd.c, lfs.c
So instead of `lfs_file_rawopencfg`, it's now `lfs_file_opencfg_`.
The "raw" prefix is annoying, doesn't really add meaning ("internal" would have been better), and gets in the way of finding the relevant function implementations.
I have been using `_`s as suffixes for unimportant name collisions in other codebases, and it seems to work well at reducing wasted brain cycles naming things. Adopting it here avoids the need for "raw" prefixes.
It's quite a bit like the use of prime symbols to resolve name collisions in math, e.g. $x' = x + 1$. Which is even supported in Haskell and is quite nice there.
And the main benefit: Now if you search for the public API name, you get the internal function first, which is probably what you care about.
Here is the exact script:
``` bash
sed -i …
```
=> Rename internal functions _raw* -> _*_

.github/workflows/post-release.yml, .github/workflows/release.yml, .github/workflows/status.yml, .github/workflows/test.yml, bd/lfs_emubd.c, lfs.c, lfs.h, lfs_util.c, lfs_util.h, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, tests/test_alloc.toml, tests/test_dirs.toml, tests/test_files.toml, tests/test_orphans.toml
This release brings in some heavily requested minor features. Thanks to everyone who has contributed/provided feedback!
Bringing in:
- #886
- #909
- #912
- #913
- #914
- #915
- #916
- #917
---
- `lfs_rename` now returns LFS_ERR_NOTDIR if the source is a regular file and the destination is a directory. This better aligns with POSIX.
- Defining LFS_FILE_MAX > 2147483647 is no longer supported. It's unclear if this ever worked, and at least half the file API was unusable in this state.
- `lfs_fs_gc` can now compact metadata ([#913](https://github.com/littlefs-project/littlefs/pull/913))
This is controlled by the new optional `compact_thresh` configuration option. mdirs above `compact_thresh` will be eagerly compacted during `lfs_fs_gc`, making it less likely …
=> Minor release: v2.9

lfs.c
By "luck" the previous code somehow managed to not be broken, though it was possible to traverse the same file twice in `lfs_fs_traverse/size` (which is not an error).
The problem was an underlying assumption in `lfs_dir_get` that it would never be called when the requested id is pending removal because of a powerloss. The assumption was either:
1. `lfs_dir_find` would need to be called first to find the id, and it would correctly toss out pending-rms with LFS_ERR_NOENT.
2. `lfs_fs_mkconsistent` would be implicitly called before any filesystem traversals, cleaning up any pending-rms. This is at least true for allocator scans.
But, as noted by @andriyndev, both `lfs_fs_traverse` and `lfs_fs_size` can call `lfs_fs_get` with a pending-rm id if called in a readonly context.
---
By "luck" this …
=> Fix synthetic move underflows in lfs_dir_get

bd/lfs_emubd.c, bd/lfs_emubd.h, lfs.c, tests/test_dirs.toml, tests/test_files.toml, tests/test_interspersed.toml, tests/test_move.toml, tests/test_seek.toml, tests/test_superblocks.toml, tests/test_truncate.toml
Long story short we aren't calling sync correctly in littlefs. This fixes that.
Some forms of storage, mainly anything with an FTL, eMMC, SD, etc, do not guarantee a strict write order for writes to different blocks. In theory this is what bd sync is for, to tell the bd when it is important for the writes to be ordered.
Currently, littlefs calls bd `sync` after committing metadata. This is useful as it ensures that user code can rely on `lfs_file_sync` for ordering external side-effects.
But this is insufficient for handling storage with out-of-order writes.
Consider the simple case of a file with one data block:
1. `lfs_file_write(blablabla)` => writes data into a new data block
2. `lfs_file_sync()` => commits metadata to point to the new data block
But with out-of-order writes, the bd …
=> Fix sync issue where data writes could appear before metadata writes

lfs.c, lfs.h, tests/test_alloc.toml
There were reports of a `DivideByZero` exception in [esp_littlefs](https://github.com/joltwallet/esp_littlefs) when the filesystem was completely full. @huming2207 was able to get a [stacktrace](https://github.com/joltwallet/esp_littlefs/issues/183#issuecomment-2060156353), and it points to the logging line in this PR. We're still figuring out if this is the certainly the cause, but the current code looks like an overlooked bug from #912. 
Might address https://github.com/joltwallet/esp_littlefs/issues/183
Original original thread: https://esp32.com/viewtopic.php?f=13&t=39197&p=130708
=> Fix DivideByZero exception when filesystem is completely full.

SPEC.md, lfs.c, tests/test_superblocks.toml
The documentation does not match the implementation here. The intended behavior of superblock expansion was to duplicate the current superblock entry into the new superblock:
```
.--------.  .--------.
.|littlefs|->|littlefs|
||bs=4096 | ||bs=4096 |
||bc=256  | ||bc=256  |
||crc32   | ||root dir|
||        | ||crc32   |
|'--------' |'--------'
'--------'  '--------'
```
The main benefit is that we can rely on the magic string "littlefs" always residing in blocks 0x{0,1}, even if the superblock chain has multiple superblocks.
The downside is that earlier superblocks in the superblock chain may contain out-of-date configuration. This is a bit annoying, and risks hard-to-reach bugs, but in theory shouldn't break anything as long as the filesystem is aware of this.
Unfortunately this was lost …
=> Duplicate the superblock entry during superblock expansion, fix missing magic

.github/workflows/release.yml
We probably always want a human involved in the final step of publishing a release. 1. To allow editing of the release notes before notifying users, and 2. to avoid any issues with rogue scripts (who doesn't want 1000 release notifications?).
Especially now that releases may trigger additional post-release scripts.
=> Limit release script to only draft releases

README.md
- [pico-littlefs-usb]
Implemented by @oyama, pico-littlefs-usb provides an easy interface to littlefs by emulating a FAT12 filesystem over USB.
There are some tradeoffs to this, but being able to mount a littlefs device without installing additional drivers is very nice. Maybe in the future devices could provide both a FAT and raw endpoint for easy/advanced filesystem access.
- [mklittlefs]
Implemented by @earlephilhower, mklittlefs is a command line interface that seems to be used by the ESP8266 and RP2040 ecosystems. It deserves a mention.
Eventually, these (and most links in the README.md) will move to an external wiki. Eventually...
[pico-littlefs-usb]: https://github.com/oyama/pico-littlefs-usb
[mklittlefs]: https://github.com/earlephilhower/mklittlefs
=> Add links to pico-littlefs-usb (FAT12 emulation) and mklittlefs

lfs.c
- Using the master branch code, the footprint size of the gcc compilation under Windows is as follows
```log
text    data     bss     dec     hex filename
33440       0       0   33440    82a0 lfs.o
208       0       0     208      d0 lfs_util.o
33648       0       0   33648    8370 (TOTALS)
```
- After this change, the compilation footprint is as follows
```log
text    data     bss     dec     hex filename
33228       0       0   33228    81cc lfs.o
208       0       0     208      d0 lfs_util.o
33436       0       0   33436    829c (TOTALS)
```
- The optimization result can be obtained,Compiles without error or warning.
```log
0x8370- 0x829c = 0xD4
0xD4/0x8370 = 0.63%
```
- gcc version
```log
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe …
```
=> Write the detect cycles function as a function to optimize code

lfs.c
More printf warnings in LFS_TRACE found by @stefano-zanotti:
- block_cycles is signed and should use PRId32
- flags is signed (which is a bit weird) and should be cast for %x
Unfortunately exactly what PRI* expands to is dependant on both the compiler and the underlying architecture, so I don't think it's possible for us to catch these mistakes with CI...
Found by @stefano-zanotti
See https://github.com/littlefs-project/littlefs/issues/982 for more info
=> Fix some more LFS_TRACE format specifiers

lfs.c, tests/test_seek.toml
In the previous implementation of lfs_file_seek, we calculated the new offset using signed arithmetic before checking for possible overflow/underflow conditions. This results in undefined behavior in C.
Fortunately for us, littlefs is now limited to 31-bit file sizes for API reasons, so we don't have to be too clever here. Doing the arithmetic with unsigned integers and just checking if we're in a valid range afterwards should work.
---
Found by @m-kostrzewa and @lucic71
Original tests showing the issue provided by @m-kostrzewa here: https://github.com/littlefs-project/littlefs/issues/1002
Alternative fix proposed by @lucic71 here: https://github.com/littlefs-project/littlefs/pull/1017
=> Fix seek undefined behavior on signed integer overflow

lfs.c, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, tests/test_superblocks.toml
I've been trying to dig into some of the early LFS_ERR_NOSPC errors users have been seeing. Some of the problem is that littlefs returns LFS_ERR_NOSPC for both "no space" errors, and internally whenever metadata can't fit in a block/mdir. This has made tracking down the actual root cause a bit tricky.
I did at least find one bug: In mdir compaction we weren't correctly adjusting `commit->end` to reserve space for commit-related metadata (checksums, tail pointers, etc) when `metadata_max` == `prog_size`.
This went unnoticed due to a lack of testing and requiring `metadata_max` == `prog_size`.
Added a quick test to prevent regression, and also added a few more asserts to `lfs_init` related to possible `metadata_max` configuration mistakes.
Found by @ajheck, @dpkristensen, @NLLK, and likely …
=> Fix metadata_max==prog_size commit->end calculation

README.md
These two small libraries provide examples of error-correction compatible with littlefs (or any filesystem really):
- [ramcrc32bd][ramcrc32bd]
- [ramrsbd][ramrsbd]
It would be nice to eventually provide these as drop-in solutions, but right now it's not really possible without breaking changes to littlefs's block device API.
In the meantime, ramcrc32bd and ramrsbd at least provide example implementations that can be adapted to users' own block devices.
[ramcrc32bd]: https://github.com/geky/ramcrc32bd
[ramrsbd]: https://github.com/geky/ramrsbd
=> Add links to ramcrc32bd and ramrsbd

lfs.c, tests/test_paths.toml
This PR includes a number of tweaks to path parsing behavior to better align with POSIX. Better aligning with POSIX should make things less surprising for users, which is always a good thing.
This is the relevant section in POSIX: [4.16 Pathname Resolution](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap04.html#tag_04_16).
Though note there are still some differences, listed below.
In addition to these changes, this PR includes a rewrite of the [`tests/test_paths.toml`](https://github.com/littlefs-project/littlefs/blob/fix-trailing-slashes/tests/test_paths.toml) (+7269/-207 lines, +20 cases, +260 perms) to more aggressively cover path parsing corner cases. That being said, it's unreasonable to expect me to think of every possible corner case on the first (or nth?) try, …
=> paths: Revisit path parsing, fix trailing slash behavior

.github/workflows/test.yml
Looks like I missed a line during refactoring, resulted in only x86 sizes being reported in GitHub statuses.
\< Insert rant about GHA making a mess of commit histories \>
Related: https://github.com/littlefs-project/littlefs/pull/1026
=> gha: Fix x86-only statuses

lfs.c, scripts/prettyasserts.py
Assert that the IO functions (especially the `sync` function when using non-caching storage) are provided by the user.
=> Assert on NULL IO functions

.github/workflows/release.yml, .github/workflows/status.yml, .github/workflows/test.yml, README.md, lfs.c, lfs.h, lfs_util.h, runners/bench_runner.c, runners/bench_runner.h, runners/test_runner.c, runners/test_runner.h, scripts/prettyasserts.py, tests/test_paths.toml, tests/test_seek.toml, tests/test_superblocks.toml
In hindsight this should have probably been split into multiple releases. Attempting to merge unrelated PRs into the same minor release led to some issues being unresolved much longer than necessary.
Main new features include LFS_DEFINES (#1004) by @yamt as an easier way to override lfs_utils.h, and a rework of the internal path parser to better align with POSIX/user expectations.
Thanks to everyone who contributed!
Bringing in:
- #997
- #1004
- #1013
- #1026
- #1027
- #1031
- #1038
- #1046
- #1052
- #1053
---
This holiday themed release brings in some minor, but highly requested, features.
- Path parsing has been reworked internally to better align with POSIX/user expectations in a number of corner cases. This changes behavior of paths with trailing …
=> Minor release: v2.10

lfs.c, tests/test_seek.toml
In v2.5 (https://github.com/littlefs-project/littlefs/pull/632 specifically), we introduced an optimization to avoid rereading data when seeking inside the file cache. Unfortunately this used a slightly wrong condition to check if the cache was "live", which meant seeks from end-of-blocks could end up with invalid caches and wrong data. Not great.
The problem is the nuance of when a file's cache is "live":
1. The file is marked as LFS_F_READING or LFS_F_WRITING.
But we can't reuse the cache when writing, so we only care about LFS_F_READING.
2. `file->off != lfs->cfg->block_size` (end-of-block).
This is an optimization to avoid eagerly reading blocks we may not actually care about.
We weren't checking for the end-of-block case, which meant if you seeked _from_ the end of a block to a …
=> Fix incorrect cache reuse when seeking from end-of-block

scripts/prettyasserts.py, scripts/test.py
Many of these require a r'' string context to avoid errors like:
scripts/test.py:105: SyntaxWarning: invalid escape sequence '\s'
=> scripts: Fixed several SyntaxWarning for python test helpers

lfs.c
Using negate on a bool causes a warning when compiling with MSVC 19.X:
```
littlefs\lfs.c(2561): error C2220: the following warning is treated as an error
littlefs\lfs.c(2561): warning C4804: '-': unsafe use of type 'bool' in operation
```
=> Fix for "unsafe use of type bool" warning when compiling with MSVC.

lfs.c, tests/test_dirs.toml
When removing a file, we mark all open handles as "removed" (pair={-1,-1}) to avoid trying to later read metadata that no longer exists. Unfortunately, this also includes open dir handles that happen to be pointing at the removed file, causing them to return LFS_ERR_CORRUPT on the next read.
The good news is this is _not_ actual filesystem corruption, only a logic error in `lfs_dir_read`.
We actually already have logic in place to nudge the dir to the next id, but it was unreachable with the existing logic. I suspect this worked at one point but was broken during a refactor due to lack of testing.
---
Fortunately, all we need to do is _not_ clobber the handle if the internal type is a dir. Then the dir-nudging logic can correctly take over.
I've also added `test_dirs_remove_read` to test …
=> Fix dir iteration being broken by concurrent removes

.github/workflows/test.yml, bd/lfs_filebd.c
This does not compile when LFS_FILEBD_YES_TRACE is set, due to a cast to a `lfs_file_t` instead of `lfs_filebd_t`
=> Changed cast to correct type when trace is enabled for filebd

lfs.c
lfs_gstate_t was assumed to be a packed array of uint32_t, but this is not always guaranteed. Access the fields directly instead of attempting to loop over an array of uint32_t
Fixes clang tidy warnings about use of uninitialized memory accessed.
=> fix: avoid assuming struct packing

lfs_util.h
If `LFS_CRC` is defined, we define a wrapper function in the header file itself instead of referring to a function implemented later in `lfs_utils.c`. In that case we should declare that wrapper function to be `static` so that we don't end up with multiple definitions of the `lfs_crc` function if the header file (as is quite usual) gets included in multiple compile units.
Additionally it can also be declared `inline` to match the other functions. And, there was a missing semicolon meaning one would have to include an extra semicolon in their `#define` macro to make everything compile without errors. Adding in the semicolon won't break any existing users that already included it themselves.
=> lfs_crc should be static if LFS_CRC is defined

lfs_util.h
In 16 bit and 8 bit architectures, overflow and underflow issues were occuring while using functions lfs_frombe32 and lfs_fromle32.
=> fix: added uint32_t cast to the bitshift places

lfs.c, tests/test_orphans.toml, tests/test_relocations.toml
Long story short: There is a specific case where removing a directory can trigger a deorphan pass, but `lfs_remove` did not check for this, would try to clean up the (already cleaned) directory orphan, and trigger an assert:
``` c
lfs.c:4890:assert: assert failed with false, expected eq true
LFS_ASSERT(lfs_tag_size(lfs->gstate.tag) > 0x000 || orphans >= 0);
```
The specific case being a remove commit that triggers a relocation that creates an orphan.
This is also possible in lfs_rename, but only if you're renaming a directory that implies a remove, which is a pretty rare operation.
---
This was probably an oversight introduced in the non-recursive commit logic rework (https://github.com/littlefs-project/littlefs/pull/658).
Fortunately the fix is to just check if we even have an orphan …
=> Fix double deorphan caused by relocation mid dir remove

runners/bench_runner.c, runners/test_runner.c, scripts/bench.py, scripts/test.py
"make test" on macOS:
```
using runner: ./runners/test_runner
found 19 suites, 188 cases, 11242/11770 permutations
running test_alloc: 12/12 cases, 207/207 perms
running test_attrs: 4/4 cases, 20/20 perms
running test_badblocks: 4/4 cases, 300/300 perms
running test_bd: 5/5 cases, 85/85 perms
running test_compat: 17/17 cases, 205/205 perms
running test_dirs: 15/15 cases, 450/450 perms, 1756pls!
running test_entries: 8/8 cases, 32/32 perms
running test_evil: 8/8 cases, 105/105 perms
running test_exhaustion: 5/5 cases, 85/85 perms
running test_files: 10/10 cases, 7155/7155 perms, 9410pls!
running test_interspersed: 4/4 cases, 190/190 perms, 2835pls!
running test_move: 17/17 cases, 161/161 perms, 157pls!
running test_orphans: 6/6 cases, 50/50 perms, 846pls!
running test_paths: 33/33 cases, …
```
=> adapt the linker sections usage to mach-o

.github/workflows/test.yml, lfs.c, lfs.h, tests/test_shrink.toml, tests/test_superblocks.toml
This PR adds a new `lfs_fs_shrink`, which functions similarly to `lfs_fs_grow`, but supports reducing the block count.
This functions first checks that none of the removed block are in use. If it is the case, it will fail.
Closes #1093
=> Add support for shrinking a filesystem

.github/workflows/test.yml, Makefile, lfs.c, lfs.h, lfs_util.h, runners/bench_runner.c, runners/test_runner.c, scripts/bench.py, scripts/changeprefix.py, scripts/test.py, tests/test_orphans.toml, tests/test_relocations.toml, tests/test_shrink.toml, tests/test_superblocks.toml
A small minor release, driven by features proposed by @sosthene-nitrokey and @yamt, with bug fixes from @DvdGiessen, @selimkeles, and yours truly.
Bringing in:
- https://github.com/littlefs-project/littlefs/pull/1090
- https://github.com/littlefs-project/littlefs/pull/1091
- https://github.com/littlefs-project/littlefs/pull/1094
- https://github.com/littlefs-project/littlefs/pull/1095
- https://github.com/littlefs-project/littlefs/pull/1099
- https://github.com/littlefs-project/littlefs/pull/1100
- https://github.com/littlefs-project/littlefs/pull/1104
---
A small minor release, driven by features proposed by @sosthene-nitrokey and @yamt, with bug fixes from @DvdGiessen, @selimkeles, and yours truly.
- Thanks to @sosthene-nitrokey, `lfs_fs_grow` now …
=> Minor release: v2.11

lfs.c
Sorry my English is very poor, so I use machine translation.
When the user incorrectly sets lookahead_size, if lookahead_size > (block_count / 8), gc might try to populate the lookahead buffer each time.
I'm not sure if this PR is the optimal solution. Perhaps it should help users set the correct value during the mount stage.
Because similar processing is also done in the lfs_format_ and lfs_alloc_scan functions, in fact, this processing can be completely optimized out.
=> perf: gc might try to populate the lookahead buffer each time

lfs.c
If lfs_bd_read fails, lfs_fcrc_fromle32 will read uninitialized memory, and hasfcrc will be set to true.
This may end up in a "working" state later due to crcs not matching. but it's hard to follow if that woud be the case.
=> fix: add missing return causing uninitialized reads

lfs.c
When dealing with large block sizes (128KiB, for example) and lots of small files (64 bytes and smaller, in the case of 128KiB block sizes), it's possible to run into the constraint where it seems dir->count can't exceed 1023. For example, here https://github.com/littlefs-project/littlefs/blob/master/lfs.c#L1372. This can result in cases where you can fail to create new files even though you have plenty of disk space left.
=> fix: compact when dir count hits 0x3ff

README.md
For your consideration to possibly add in the README.
littlefs-toy is a small command-line tools with _tar_ like syntax for creating and modifying littlefs images. It supports working on littlefs filesystems embedded inside another file (firmware image, etc.) and can auto-detect blocksize when working on existing littlefs images.
=> Add littlefs-toy to the related projects section.
